The pull requests query is incorrect if one of the parameters is not given
juliangruber/find-pull-request-action pull request #10
Opened 2020-09-03 20:27 UTC by RoKish

### Description

If either `branch` or `base` input parameter is not specified, the query that is used to retrieve pull requests is incorrect. 

### Steps to reproduce

Define `find-pull-request-action` with `base` parameter undefined:

```
- name: Find Pull Request
    uses: juliangruber/find-pull-request-action@v1.2.0
    id: find-pull-request
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      branch: my-branch-name
```

In that case, the action creates a query with an empty value for `base` query parameter. Such a query always returns no results.

```
https://api.github.com/repos/juliangruber/find-pull-request-action/pulls?state=open&head=juliangruber:my-branch-name&base=
```

2020-09-04 16:00 UTC, juliangruber requested changes
there is more happening in the pr than advertised, could you please reduce it to just the query fix?

2020-09-04 16:00 UTC, juliangruber commented on index.js
> -  const token = core.getInput('github-token')
could you please undo this reordering?

2020-09-04 18:37 UTC, RoKish commented on index.js
> -  const token = core.getInput('github-token')
Done

2020-09-04 18:38 UTC, RoKish commented
Hi Julian, thank you for the quick reply. I have removed everything not related to the issue from the pull request.

2020-09-04 20:20 UTC, juliangruber requested changes
https://github.com/juliangruber/find-pull-request-action/blob/master/action.yml#L13 needs to be adjusted as well. Thanks!

2020-09-04 20:20 UTC, juliangruber commented on index.js
> +  }
could you please keep the previous ordering of all `core.getInput` calls first?

2020-09-04 21:44 UTC, RoKish commented on index.js
> +  }
Done

2020-09-05 10:57 UTC, juliangruber requested changes

2020-09-05 10:57 UTC, juliangruber commented on index.js
>    const branch = core.getInput('branch')
all `core.getInput` first in this function please

2020-09-09 04:32 UTC, RoKish commented on index.js
>    const branch = core.getInput('branch')
Done

2020-09-09 08:17 UTC, juliangruber approved these changes

2020-09-09 08:17 UTC, merged

2020-09-09 08:19 UTC, juliangruber commented
Thank you! https://github.com/juliangruber/find-pull-request-action/releases/tag/v1.2.1